---
- assert: { that: "ansible_system_vendor == 'HP'" }

#following expects that your system has only same type disks on thats why this incredible stupid hack
- name: Identifying firmware RPM for disk drives
  shell: "yum search `hpssacli ctrl all show config detail | grep 'Model:' |grep -E '(ATA|HP)' | sort -u| awk '{print $NF}'` | grep -i firmware-hdd | awk '{print $1}' | grep `uname  -m`"
  register: fw_rpm
  changed_when: false
  ignore_errors: yes

- name: running generic tasks for all firmware things
  include_tasks: firmware_installer.yml
  with_items: "{{ fw_rpm.stdout_lines }}"
  when: fw_rpm.rc == 0
