---
- include_tasks: prerequisite.yml
  tags:
    - ilo
    - system-rom
    - disk-controller
    - disk-drive
    - power-management-controller
    - intel-network-adapter
    - mellanox-network-adapter

- include_tasks: ilo.yml
  tags:
    - ilo
  when: upgrade_ilo_firmware

- include_tasks: system_rom.yml
  tags:
   - system-rom
  when: upgrade_system_rom_firmware

- include_tasks: disk_controller.yml
  tags:
   - disk-controller
  when: upgrade_disk_controller_firmware

- include_tasks: disk_drive.yml
  tags:
   - disk-drive
  when: upgrade_disk_drive_firmware

- include_tasks: power_management_controller.yml
  tags:
   - power-management-controller
  when: upgrade_power_management_controller_firmware

- include_tasks: intel_network_adapter.yml
  tags:
   - intel-network-adapter
  when: upgrade_intel_network_adapter_firmware

#- include_tasks: mellanox_network_adapter.yml
#  tags:
#   - mellanox-network-adapter
#  when: upgrade_mellanox_network_adapter_firmware
