---
 - name: Identifying System ROM device
   shell: dmidecode -t 0 |grep Version:| awk '{print $NF}'
   register: systemrom
   check_mode: no

 - debug:
     msg: "{{ systemrom }}"

 - name: Identifying firmware RPM for System ROM
   shell: "yum search {{systemrom.stdout}} system|grep HP |awk '{print $1;exit}'"
   register: fw_rpm
   changed_when: False
   ignore_errors: True
   check_mode: no

 - name: running generic tasks for all firmware things for  {{systemrom}}
   include_tasks: firmware_installer.yml
   with_items: "{{ fw_rpm.stdout_lines }}"
   when: fw_rpm.rc == 0
